int decrypt(char* fileName, bloc64* key);
int crypt(char* fileName, bloc64* key);
int checkFileAscii(char* fileName, char* repository);
int saveKey(char* fileName, char* key);
int readKeyFromFile(char* fileName, char* key);
int checkKey(char* key);
int checkKeyFile(char* fileName);
int checkMode(char* mode);
int checkFile(char* fileName, int progMode);
int isFileInDirectory(char* fileName, char* dirPath);
int directoryExists(char* directoryName);
int checkStructure();
